# This is a basic workflow to help you get started with Actions

name: PyInstaller (macos)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_mac:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with pyinstaller
        run: pyinstaller -w --osx-bundle-identifier com.akond.teda.teda_fits teda/teda_fits.py
        
      - name: ZIP application
        run: |
          cd dist
          zip -r teda_fits.app.zip teda_fits.app
          cd ..
          
      - name: Collect executable
        uses: actions/upload-artifact@v2
        with:
          name: teda_fits.app
          path: dist/teda_fits.app.zip

# # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
